agent_count: 1
run_id: identityandview_1H_small
log_path: /home/desabh/iclr/NewbornEmbodiedTuringTest/data/models/${run_id}
mode: full
train_eps: 1000
test_eps: 20
num_conditions: 50
hydra.job.chdir: True
cuda: 0
experiment: identityandview

defaults:
  - _self_
  - Agent: basic
  - Environment: identityandview
  - hydra
