Brain:
  reward: supervised
  batch_size: 512
  buffer_size: 2048
  algorithm: PPO
  policy: CnnPolicy
  seed: 42
  encoder: small
  train_encoder: True
Body:
  type: basic
  dvs: False
Environment:
  # condition
  object: "object2"
  # generic config
  executable_path: /home/mchivuku/projects/embodied_pipeline/ICLR/newbornmain/data/executables/binding/binding.x86_64
  record_chamber: False
  record_agent: False
  recording_frames: 100
Config:
  run_id: "binding_object1"
  num_brains: 1
  mode: "full"
  train_eps: 1000
  test_eps: 20
  output_dir: "/data/mchivuku/embodiedai/neurips_experiments/binding/base_agents_new/small/object2_exp5"

