"""Simplifies imports for encoders"""
from .resnet18 import Resnet18CNN
from .resnet10 import Resnet10CNN
from .dinov1 import DinoV1
from .dinov2 import DinoV2
from .sam import SegmentAnything
from .vit import ViT
from .cnnlstm import CNNLSTM
from .frozensimclr import FrozenSimCLR
