name: "Render Docs"

on:
  push:
    branches:
      - fix/doc-deploy
      # - main
      # - dev
  # pull_request:
    # branches:
      # - main
      # - dev

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: docsBuilder
          environment-file: docs/environment.yml

      - name: Sphinx build
        run: |
          sphinx-build -M html docs/source/ docs/build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # change to only main branch (see below)
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/fix/doc-deploy') }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
