name: "Render Docs"

on:
  push:
    branches:
      - fix/doc-deploy
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.12

      - name: Cache pip
        uses: actions/cache@v3
        id: cache-pip
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
      - name: Install pip
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          pip install pip install setuptools==65.5.0 pip==21 --disable-pip-version-check --no-compile
      - name: Install Dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          pip install -r docs/requirements.txt --disable-pip-version-check --no-compile

      - name: Sphinx build
        run: |
          sphinx-build --jobs auto -b html docs/source/ docs/build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # change to only main branch (see below)
        # if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true
