name: Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  docstrings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"
          cache: "pip" # caching pip dependencies
            # Install your linters here

      # - name: Change setuptools version
      #   run: pip install setuptools==65.5.0

      # - name: Change pip version
      #   run: pip install pip==21

      - name: Install pylint
        run: pip install pylint

      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      - name: Run Linter
        uses: wearerequired/lint-action@v2
        with:
          pylint: true
          pylint_args: "--disable=all --enable=C0114 --enable=C0115 --enable=C0116"
          # checks for:
          ## missing module, class, and method docstrings
  unused_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"
          cache: "pip"  # caching pip dependencies
            # Install your linters here

      # - name: Change setuptools version
      #   run: pip install setuptools==65.5.0

      # - name: Change pip version
      #   run: pip install pip==21

      - name: Install pylint
        run: pip install pylint

      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      - name: Run Linter
        uses: wearerequired/lint-action@v2
        with:
          pylint: true
          pylint_args: "--disable=all --enable=W0612 --enable=W0613"
          # checks for:
          ## unused arguments, and unused variables
